### ISSUE TITLE
Undefined variable $testTemplateConfig

### ISSUE THREAD

**Issue by Zhehan-Z** [zhiguai/LoveCards#1]
Undefined variable $testTemplateConfig
URL: http://MySite/admin/System/view.
Environment: PHP 8.1, Fresh install, V2.1.0

**Comment by zhiguai** [comment]
> Undefined variable $testTemplateConfig
> URL: http://MySite/admin/System/view.
> Environment: PHP 8.1, Fresh install, V2.1.0

这是您在开发模板时出现的吗？

**Comment by AntDock** [comment]
尝试使用PHP 8.0.2，依然存在该问题，直接安装未修改任何配置，模版为默认
